<%@ Page Language="C#" AutoEventWireup="True" CodeBehind="TaskGrade.aspx.cs" Inherits="RailExamWebApp.Task.TaskGrade" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>作业信息 - 作业成绩</title>
    <script type="text/javascript">
        function imgBtns_onClick(btn)
        {
	        switch(btn.type)
	        {
	            case "0":
	            {
	                window.location.href = "javascript:__doPostBack('dvTaskResult','Edit$0')";
	                
	                break;
	            }
	            case "1":
	            {
	                window.location.href = "javascript:__doPostBack('dvTaskResult$ctl01','')";
	            
	                break;
	            }
	            case "2":
	            {
	                window.location.href = "javascript:__doPostBack('dvTaskResult','Cancel$0')";
	                
	                break;
	            }
	            default:
	            {
	                alert("状态错误！");
	                
	                break;
	            }
        	}
        }
    </script>
</head>
<body>
    <form id="form1" runat="server">
        <div id="page">
            <div id="head">
                <div id="location">
                    <div id="desktop" onclick="window.location='../Main/Desktop.aspx'"></div><div id="parent">
                        作业信息
                    </div>
                    <div id="separator">
                    </div>
                    <div id="current">
                        <b>作业成绩</b>
                    </div>
                </div>
                <div id="welcomeInfo">
                    <%=RailExamWebApp.Common.Class.PrjPub.WelcomeInfo%>
                </div>
                <div id="button">
                    <img id="editButton" runat="server" alt="" onclick="imgBtns_onClick(this);" src="../Common/Image/edit.gif"
                        type="0" />
                    <img id="updateButton" runat="server" alt="" onclick="imgBtns_onClick(this);" src="../Common/Image/save.gif"
                        type="1" />
                    <img id="updateCancelButton" runat="server" alt="" onclick="imgBtns_onClick(this);"
                        src="../Common/Image/cancel.gif" type="2" />
                </div>
            </div>
            <div id="content">
                <asp:DetailsView ID="dvTaskResult" runat="server" AutoGenerateDeleteButton="false"
                    AutoGenerateEditButton="false" AutoGenerateInsertButton="false" AutoGenerateRows="False"
                    DataSourceID="odsTaskResult" GridLines="None" OnModeChanged="dvTaskResult_OnModeChanged"
                    Width="100%">
                    <Fields>
                        <asp:TemplateField>
                            <ItemTemplate>
                                <table class="contentTable">
                                    <tr>
                                        <td width="15%">
                                            培训类别
                                        </td>
                                        <td width="30%">
                                            <asp:Label ID="lblTrainTypeName" runat="server" Text='<%# Eval("TrainTypeName") %>'>
                                            </asp:Label>
                                        </td>
                                        <td width="15%">
                                            作业名称
                                        </td>
                                        <td>
                                            <asp:Label ID="lblPaperName" runat="server" Text='<%# Eval("PaperName") %>'>
                                            </asp:Label>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td width="15%">
                                            作业人
                                        </td>
                                        <td width="30%">
                                            <asp:Label ID="lblEmployeeName" runat="server" Text='<%# Eval("EmployeeName") %>'>
                                            </asp:Label>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td width="15%">
                                            作业开始时间
                                        </td>
                                        <td>
                                            <asp:Label ID="lblBeginTime" runat="server" Text='<%# Eval("BeginTime") %>'>
                                            </asp:Label>
                                        </td>
                                        <td width="15%">
                                            作业结束时间
                                        </td>
                                        <td width="30%">
                                            <asp:Label ID="lblEndTime" runat="server" Text='<%# Eval("EndTime") %>'>
                                            </asp:Label>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td width="15%">
                                            作业共花费时间
                                        </td>
                                        <td>
                                            <asp:Label ID="lblUsedTimeString" runat="server" Text='<%# Eval("UsedTimeString") %>'>
                                            </asp:Label>
                                        </td>
                                        <td width="15%">
                                            自动评分分数
                                        </td>
                                        <td width="30%">
                                            <asp:Label ID="lblAutoScore" runat="server" Text='<%# ((decimal)Eval("AutoScore")).ToString("0.00") + " 分" %>'>
                                            </asp:Label>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td width="15%">
                                            评分分数
                                        </td>
                                        <td width="30%">
                                            <asp:Label ID="lblScore" runat="server" Text='<%# ((decimal)Eval("Score")).ToString("0.00") + " 分" %>'>
                                            </asp:Label>
                                        </td>
                                        <td width="15%">
                                            评分人
                                        </td>
                                        <td>
                                            <asp:Label ID="lblJudgeName" runat="server" Text='<%# Eval("JudgeName") %>'>
                                            </asp:Label>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td width="15%">
                                            正确率（百分比）
                                        </td>
                                        <td width="30%">
                                            <asp:Label ID="lblCorrectRate" runat="server" Text='<%# Eval("CorrectRate") + "%" %>'>
                                            </asp:Label>
                                        </td>
                                        <td width="15%">
                                            是否通过
                                        </td>
                                        <td>
                                            <asp:Label ID="lblIsPass" runat="server" Text='<%# (bool)Eval("IsPass") ? "是" : "" %>'>
                                            </asp:Label>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td width="15%">
                                            作业人结果状态
                                        </td>
                                        <td width="30%">
                                            <asp:Label ID="lblStatusName" runat="server" Text='<%# Eval("StatusName") %>'>
                                            </asp:Label>
                                        </td>
                                        <td width="15%">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td width="15%">
                                            备注
                                        </td>
                                        <td colspan="3" width="30%">
                                            <asp:Label ID="Label1" runat="server" Text='<%# Eval("Memo") %>'>
                                            </asp:Label>
                                        </td>
                                    </tr>
                                </table>
                            </ItemTemplate>
                            <EditItemTemplate>
                                <table class="contentTable">
                                    <tr>
                                        <td width="15%">
                                            培训类别
                                        </td>
                                        <td width="30%">
                                            <asp:Label ID="lblTrainTypeName" runat="server" Text='<%# Eval("TrainTypeName") %>'>
                                            </asp:Label>
                                        </td>
                                        <td width="15%">
                                            作业名称
                                        </td>
                                        <td>
                                            <asp:Label ID="lblPaperName" runat="server" Text='<%# Bind("PaperName") %>'>
                                            </asp:Label>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td width="15%">
                                            作业人
                                        </td>
                                        <td width="30%">
                                            <asp:Label ID="lblEmployeeName" runat="server" Text='<%# Bind("EmployeeName") %>'>
                                            </asp:Label>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td width="15%">
                                            作业开始时间
                                        </td>
                                        <td>
                                            <asp:TextBox ID="txtBeginTime" runat="server" Text='<%# Bind("BeginTime") %>'>
                                            </asp:TextBox>
                                        </td>
                                        <td width="15%">
                                            作业结束时间
                                        </td>
                                        <td width="30%">
                                            <asp:TextBox ID="txtEndTime" runat="server" Text='<%# Bind("EndTime") %>'>
                                            </asp:TextBox>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td width="15%">
                                            作业共花费时间
                                        </td>
                                        <td>
                                            <asp:Label ID="lblUsedTimeString" runat="server" Text='<%# Eval("UsedTimeString") %>'>
                                            </asp:Label>
                                        </td>
                                        <td width="15%">
                                            自动评分分数
                                        </td>
                                        <td width="30%">
                                            <asp:Label ID="lblAutoScore" runat="server" Text='<%# ((decimal)Eval("AutoScore")).ToString("0.00") + " 分" %>'>
                                            </asp:Label>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td width="15%">
                                            评分分数
                                        </td>
                                        <td width="30%">
                                            <asp:TextBox ID="txtScore" runat="server" Text='<%# Bind("Score") %>'>
                                            </asp:TextBox>
                                        </td>
                                        <td width="15%">
                                            评分人
                                        </td>
                                        <td>
                                            <asp:Label ID="lblJudgeName" runat="server" Text='<%# Eval("JudgeName") %>'>
                                            </asp:Label>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td width="15%">
                                            正确率（百分比）
                                        </td>
                                        <td width="30%">
                                            <asp:Label ID="lblCorrectRate" runat="server" Text='<%# Eval("CorrectRate") + "%" %>'>
                                            </asp:Label>
                                        </td>
                                        <td width="15%">
                                            是否通过
                                        </td>
                                        <td>
                                            <asp:Label ID="lblIsPass" runat="server" Text='<%# (bool)Eval("IsPass") ? "是" : "" %>'>
                                            </asp:Label>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td width="15%">
                                            作业人结果状态
                                        </td>
                                        <td width="30%" colspan="3">
                                            <asp:DropDownList ID="ddlTaskResultStatus" runat="server" DataSourceID="odsTaskResultStatus"
                                                DataTextField="StatusName" DataValueField="TaskResultStatusId" SelectedValue='<%# Bind("StatusId") %>'>
                                            </asp:DropDownList>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td width="15%">
                                            备注
                                        </td>
                                        <td colspan="3">
                                            <asp:TextBox ID="txtMemo" TextMode="multiLine" runat="server" Text='<%# Bind("Memo") %>'>
                                            </asp:TextBox>
                                        </td>
                                    </tr>
                                </table>
                                <asp:HiddenField ID="hfTaskResultId" runat="server" Value='<%# Bind("TaskResultId") %>' />
                            </EditItemTemplate>
                        </asp:TemplateField>
                        <asp:CommandField ShowEditButton="True" UpdateText="保存" ControlStyle-CssClass="hiddenElement" />
                    </Fields>
                </asp:DetailsView>
            </div>
        </div>
        <div>
            <asp:ObjectDataSource ID="odsTaskResult" runat="server" DataObjectTypeName="RailExam.Model.TaskResult"
                SelectMethod="GetTaskResult" UpdateMethod="UpdateTaskResult" TypeName="RailExam.BLL.TaskResultBLL">
                <SelectParameters>
                    <asp:QueryStringParameter Name="taskResultId" QueryStringField="id" Type="Int32" />
                </SelectParameters>
            </asp:ObjectDataSource>
            <asp:ObjectDataSource ID="odsTaskResultStatus" runat="server" SelectMethod="GetTaskResultStatuses"
                TypeName="RailExam.BLL.TaskResultStatusBLL" DataObjectTypeName="RailExam.Model.TaskResultStatus">
            </asp:ObjectDataSource>
        </div>
    </form>
</body>
</html>
